version: '3.8'

services:
  # --- Microsserviços Backend ---
  order-service:
    container_name: top-restaurant_order-service_prod
    build:
      context: .
      dockerfile: services/order-service/Dockerfile.prod
    environment:
      DB_HOST: ${ORDER_DB_HOST}
      DB_PORT: ${ORDER_DB_PORT}
      DB_NAME: ${ORDER_DB_NAME}
      DB_USER: ${ORDER_DB_USER}
      DB_PASSWORD: ${ORDER_DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      WORKERS: ${WORKERS:-2}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - '5001:8000'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
    restart: unless-stopped

  payment-service:
    container_name: top-restaurant_payment-service_prod
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile.prod
    environment:
      DB_HOST: ${PAYMENT_DB_HOST}
      DB_PORT: ${PAYMENT_DB_PORT}
      DB_NAME: ${PAYMENT_DB_NAME}
      DB_USER: ${PAYMENT_DB_USER}
      DB_PASSWORD: ${PAYMENT_DB_PASSWORD}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    ports:
      - '5002:8000'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
    restart: unless-stopped

  menu-service:
    container_name: top-restaurant_menu-service_prod
    build:
      context: .
      dockerfile: services/menu-service/Dockerfile.prod
    environment:
      DB_HOST: ${MENU_DB_HOST}
      DB_PORT: ${MENU_DB_PORT}
      DB_NAME: ${MENU_DB_NAME}
      DB_USER: ${MENU_DB_USER}
      DB_PASSWORD: ${MENU_DB_PASSWORD}
    ports:
      - '5003:8000'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
    restart: unless-stopped

  # --- Frontend ---
  frontend:
    container_name: top-restaurant_frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      VITE_API_URL: ${API_URL}
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB
    restart: unless-stopped
