name: Deploy to Railway

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Test Menu Service
        run: |
          cd services/menu-service
          pip install -r requirements.txt
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/../.."
          python -m pytest tests/ -v

      - name: Test Order Service
        run: |
          cd services/order-service
          pip install -r requirements.txt
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/../.."
          python -m pytest tests/ -v

      - name: Test Payment Service
        run: |
          cd services/payment-service
          pip install -r requirements.txt
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/../.."
          python -m pytest tests/ -v

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Railway
        uses: railwayapp/railway-deploy@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: |
          railway up --service=menu-service
          railway up --service=order-service
          railway up --service=payment-service
          railway up --service=frontend
